export const studentEditTypes = {
    EDIT_NAME: "EDIT_NAME",
    EDIT_BIRTHDATE: "EDIT_BIRTHDATE",
    EDIT_ADDRESS: "EDIT_ADDRESS",
    EDIT_EMAIL: "EDIT_EMAIL",
    EDIT_PASSWORD: "EDIT_PASSWORD",
    EDIT_REPEATED_PASSWORD: "EDIT_REPEATED_PASSWORD",
};

export default studentEditTypes;